- apiVersion: "v1"
  kindsRegexp: "^secrets$"
  labelSelectors:
    matchExpressions:
    - key: "owner"
      operator: "NotIn"
      values: ["helm"]
    - key: "elemental.cattle.io/managed"
      operator: "In"
      values: ["true"]
  namespaceRegexp: "^cattle-fleet-|^fleet-|^cluster-fleet-"
- apiVersion: "apiextensions.k8s.io/v1"
  kindsRegexp: "."
  resourceNameRegexp: "elemental.cattle.io$"
- apiVersion: "elemental.cattle.io/v1beta1"
  kindsRegexp: "."
  namespaceRegexp: "^cattle-fleet-|^fleet-|^cluster-fleet-"
